# Generated by Django 2.1.5 on 2019-02-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualsymphony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongGenrePredictions',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('r_b', models.FloatField()),
                ('rap', models.FloatField()),
                ('electronic', models.FloatField()),
                ('rock', models.FloatField()),
                ('new_age', models.FloatField()),
                ('classical', models.FloatField()),
                ('reggae', models.FloatField()),
                ('blues', models.FloatField()),
                ('country', models.FloatField()),
                ('world', models.FloatField()),
                ('folk', models.FloatField()),
                ('easy_listening', models.FloatField()),
                ('jazz', models.FloatField()),
                ('vocal', models.FloatField()),
                ('punk', models.FloatField()),
                ('alternative', models.FloatField()),
                ('pop', models.FloatField()),
                ('heavy_metal', models.FloatField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'song_genre_predictions',
            },
        ),
    ]
