# Generated by Django 2.1.5 on 2019-03-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualsymphony', '0002_songgenrepredictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreSuggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_genre', models.TextField()),
                ('second_genre', models.TextField()),
                ('third_genre', models.TextField()),
                ('age_group', models.TextField()),
                ('openness', models.FloatField()),
                ('conscientiousness', models.FloatField()),
                ('extraversion', models.FloatField()),
                ('agreeableness', models.FloatField()),
                ('neuroticism', models.FloatField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'genre_suggestions',
            },
        ),
        migrations.CreateModel(
            name='RecommendationResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song1_id', models.TextField()),
                ('song1_feedback', models.BooleanField()),
                ('song2_id', models.TextField()),
                ('song2_feedback', models.BooleanField()),
                ('song3_id', models.TextField()),
                ('song3_feedback', models.BooleanField()),
                ('song4_id', models.TextField()),
                ('song4_feedback', models.BooleanField()),
                ('song5_id', models.TextField()),
                ('song5_feedback', models.BooleanField()),
                ('song6_id', models.TextField()),
                ('song6_feedback', models.BooleanField()),
                ('song7_id', models.TextField()),
                ('song7_feedback', models.BooleanField()),
                ('song8_id', models.TextField()),
                ('song8_feedback', models.BooleanField()),
                ('song9_id', models.TextField()),
                ('song9_feedback', models.BooleanField()),
                ('song10_id', models.TextField()),
                ('song10_feedback', models.BooleanField()),
                ('r_b', models.FloatField()),
                ('rap', models.FloatField()),
                ('electronic', models.FloatField()),
                ('rock', models.FloatField()),
                ('new_age', models.FloatField()),
                ('classical', models.FloatField()),
                ('reggae', models.FloatField()),
                ('blues', models.FloatField()),
                ('country', models.FloatField()),
                ('world', models.FloatField()),
                ('folk', models.FloatField()),
                ('easy_listening', models.FloatField()),
                ('jazz', models.FloatField()),
                ('vocal', models.FloatField()),
                ('punk', models.FloatField()),
                ('alternative', models.FloatField()),
                ('pop', models.FloatField()),
                ('heavy_metal', models.FloatField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'recommendation_results',
            },
        ),
    ]
